### ISSUE TITLE
YI outdoor 1080P 9.026.05_2020113201756

### ISSUE THREAD

**Issue by nonome1** [alienatedsec/yi-hack-v4#5]
Hello,
I have just tested on my camera and when I turn on the orange led is fixed 10s turns blue and flashes 10s. when i enter the ip i have nothing. how can i tell if the hack is working?

**Comment by alienatedsec** [comment]
> Hello,
> 
> I have just tested on my camera and when I turn on the orange led is fixed 10s turns blue and flashes 10s. when i enter the ip i have nothing. how can i tell if the hack is working?

It looks like you need the allwinner hack.

**Comment by nonome1** [comment]
I managed to hack my yi outdoor camera 1080p with version y21ga_0.1.5.  but I do how to integrate it into home assistant because I have the video on rstp: //192.168.*.*/ch0_0.h264.  thank's for reply
